version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwerty
      ME_CONFIG_MONGODB_URL: mongodb://admin:qwerty@mongo:27017/?authSource=admin
    depends_on:
      - mongo

  node-app:
    build: .
    image: my-node-app
    container_name: my-app
    ports:
      - 3000:5050
    environment:
      MONGO_URI: mongodb://admin:qwerty@mongo:27017/?authSource=admin
    depends_on:
      - mongo

volumes:
  mongo-data:
